[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.6.1",
    "ruff>=0.16.0",
    "sqlalchemy>=2.0.51",
    "sqlmodel>=0.0.39",
]
